/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AnalysisNewRouteImport } from './routes/analysis.new'
import { Route as AnalysisIdIndexRouteImport } from './routes/analysis.$id.index'
import { Route as AnalysisIdProgressRouteImport } from './routes/analysis.$id.progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisNewRoute = AnalysisNewRouteImport.update({
  id: '/analysis/new',
  path: '/analysis/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdIndexRoute = AnalysisIdIndexRouteImport.update({
  id: '/analysis/$id/',
  path: '/analysis/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdProgressRoute = AnalysisIdProgressRouteImport.update({
  id: '/analysis/$id/progress',
  path: '/analysis/$id/progress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/analysis/new': typeof AnalysisNewRoute
  '/analysis/$id/progress': typeof AnalysisIdProgressRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/analysis/new': typeof AnalysisNewRoute
  '/analysis/$id/progress': typeof AnalysisIdProgressRoute
  '/analysis/$id': typeof AnalysisIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/analysis/new': typeof AnalysisNewRoute
  '/analysis/$id/progress': typeof AnalysisIdProgressRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/analysis/new'
    | '/analysis/$id/progress'
    | '/analysis/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/analysis/new'
    | '/analysis/$id/progress'
    | '/analysis/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/analysis/new'
    | '/analysis/$id/progress'
    | '/analysis/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AnalysisNewRoute: typeof AnalysisNewRoute
  AnalysisIdProgressRoute: typeof AnalysisIdProgressRoute
  AnalysisIdIndexRoute: typeof AnalysisIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/new': {
      id: '/analysis/new'
      path: '/analysis/new'
      fullPath: '/analysis/new'
      preLoaderRoute: typeof AnalysisNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/': {
      id: '/analysis/$id/'
      path: '/analysis/$id'
      fullPath: '/analysis/$id/'
      preLoaderRoute: typeof AnalysisIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/progress': {
      id: '/analysis/$id/progress'
      path: '/analysis/$id/progress'
      fullPath: '/analysis/$id/progress'
      preLoaderRoute: typeof AnalysisIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AnalysisNewRoute: AnalysisNewRoute,
  AnalysisIdProgressRoute: AnalysisIdProgressRoute,
  AnalysisIdIndexRoute: AnalysisIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
